version: '3'
volumes:
  data:
services:
  db:
    image: postgres:alpine
    volumes: 
      - data:/var/lib/postgresql/data
      # Scripts
      - ./infra/postgres:/infra/postgres
      - ./infra/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      POSTGRES_PASSWORD: secret
  nginx: 
    image: nginx:alpine
    volumes:
      - ./web:/usr/share/nginx/html/
    ports:
      - 80:80
  app:
    image: python:3.6
    volumes: 
      - ./src:/src
      - ./infra/app:/infra/app
    working_dir: /infra/app
    command: bash ./app.sh
    ports:
      - 8080:8080
