version: '3'
volumes:
  data:
services:
  db:
    image: postgres:9.6
    volumes: 
      - data:/var/lib/postgresql/data
      # Scripts
      - ./infra/postgres:/infra/postgres
      - ./infra/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      POSTGRES_PASSWORD: secret
